// Redesign-only metadata. Keyed by the existing prompt ids in /data — no prompt text is modified.
// `task` powers task-first navigation; `gets` is the "You get back" line shown in results.

export type TaskId =
  | "review"
  | "compare"
  | "issues"
  | "list"
  | "draft"
  | "summarize"
  | "extract"
  | "checklist"
  | "comms";

export interface PromptMeta {
  task: TaskId;
  gets: string;
}

export interface TaskDefinition {
  id: TaskId;
  label: string;
  blurb: string;
}

export const TASKS: TaskDefinition[] = [
  { id: "review", label: "Review a document", blurb: "Read a draft and tell me what matters." },
  { id: "compare", label: "Compare two documents", blurb: "Find every substantive difference." },
  { id: "issues", label: "Find negotiation issues", blurb: "Surface the points worth fighting for." },
  { id: "list", label: "Build an issues or status list", blurb: "Turn a review into a partner-ready list." },
  { id: "draft", label: "Draft something", blurb: "First pass at a document or email." },
  { id: "summarize", label: "Summarize a matter", blurb: "Distil a large record into a short read." },
  { id: "extract", label: "Extract terms into a table", blurb: "Pull structured data out of documents." },
  { id: "checklist", label: "Build a checklist", blurb: "Every deliverable, owner, and deadline." },
  { id: "comms", label: "Write to a client or partner", blurb: "Email-ready, in a careful associate's voice." },
];

// The six task rows offered as suggestions when a search comes up empty.
export const LEAD_TASKS: TaskId[] = ["review", "compare", "issues", "list", "draft", "summarize"];

export const PROMPT_META: Record<string, PromptMeta> = {
  "ma-diligence": { task: "review", gets: "A risk table plus the five issues that could move price or closing." },
  "purchase-agreement-issues": { task: "issues", gets: "An issue list ranked must-have, tradeable, low priority." },
  "term-sheet-consistency": { task: "compare", gets: "A term-by-term table of consistencies, omissions, and shifts." },
  "disclosure-schedules": { task: "review", gets: "A clean gap list ready to send to the deal team." },
  "closing-checklist": { task: "checklist", gets: "A checklist by phase with owners, forms, and dependencies." },
  "ancillary-drafts": { task: "draft", gets: "A grouped ancillary list plus first-pass drafts." },
  "green-dot-carveout": { task: "review", gets: "A perimeter table, sequencing map, issue list, and drafting checklist." },
  "weatherford-mixed-consideration": { task: "review", gets: "A mechanics memo and a table of every inconsistency." },
  "terrestrial-spac": { task: "checklist", gets: "A sources-and-uses bridge, cap table, and minute-by-minute closing sequence." },
  "chemaf-critical-minerals": { task: "review", gets: "An integrated workstream matrix across every document." },
  "kufpec-upstream-interest": { task: "review", gets: "Five schedules: interests, consents, JV rights, liabilities, closing steps." },
  "credit-agreement-summary": { task: "summarize", gets: "A cited term summary for the deal team." },
  "commitment-paper-check": { task: "compare", gets: "A term-by-term deviation table across four documents." },
  "covenant-capacity": { task: "extract", gets: "A capacity map with the calculation steps shown." },
  "amendment-waiver": { task: "draft", gets: "A first-pass amendment plus an open-items list." },
  "conditions-precedent": { task: "checklist", gets: "A CP checklist with owner, form, deadline, and dependency." },
  "security-package": { task: "review", gets: "An entity-by-entity collateral table with gaps flagged." },
  "syndicated-refinancing": { task: "checklist", gets: "A lender matrix, payoff table, release plan, and funds flow." },
  "cloudhq-abs": { task: "review", gets: "A structure table, tranche matrix, disclosure check, and closing tracker." },
  "fiber-revenue-notes": { task: "extract", gets: "A collateral and cash-flow map plus a disclosure diligence matrix." },
  "whole-business-securitization": { task: "review", gets: "A ring-fencing map, collateral schedule, and waterfall summary." },
  "capital-structure": { task: "extract", gets: "A tranche-by-tranche map with leverage points identified." },
  "rsa-review": { task: "issues", gets: "A prioritized issue list with the leverage each term creates." },
  "critical-dates": { task: "extract", gets: "A chronological table of every deadline and its consequence." },
  "dip-order-check": { task: "compare", gets: "A provision-by-provision table of what changed." },
  "first-day-motions": { task: "summarize", gets: "A matrix of relief, basis, caps, deadlines, and dependencies." },
  "multi-affiliate-first-day": { task: "review", gets: "An entity-by-entity matrix reconciling every dollar amount." },
  "plan-disclosure": { task: "compare", gets: "A class-by-class treatment table with both sides cited." },
  "red-lobster-stalking-horse": { task: "compare", gets: "One alignment matrix plus a prioritized cure list." },
  "lease-portfolio-365": { task: "extract", gets: "A location-by-location decision matrix and exception list." },
  "psa-issue-list": { task: "issues", gets: "A prioritized issue list with proposed positions." },
  "title-survey": { task: "extract", gets: "An exception matrix with objection deadlines and cures." },
  "property-diligence": { task: "summarize", gets: "A report organized by title, occupancy, condition, and closing." },
  "student-housing-portfolio": { task: "review", gets: "A per-property dashboard plus a portfolio-level issue table." },
  "lease-abstract": { task: "extract", gets: "A full lease abstract table with amendments reconciled." },
  "estoppel-snda": { task: "compare", gets: "A comparison table with targeted revisions proposed." },
  "hartland-sale-leaseback": { task: "review", gets: "A lifecycle map of obligations triggered by the exit." },
  "re-closing": { task: "checklist", gets: "A closing checklist with owners, forms, and deadlines." },
  "asana-retail-jv": { task: "extract", gets: "A JV terms matrix plus a first-acquisition checklist." },
  "lpa-terms": { task: "extract", gets: "A fund terms matrix with every provision cited." },
  "ppm-consistency": { task: "compare", gets: "A table of inconsistencies and which document to fix." },
  "subscription-review": { task: "review", gets: "A completeness checklist and an investor follow-up list." },
  "fund-formation": { task: "checklist", gets: "A checklist with owner, dependency, and target date." },
  "jadwa-private-credit": { task: "checklist", gets: "Five deliverables: entity map, checklist, tracker, authority matrix, deployment list." },
  "side-letter-obligations": { task: "extract", gets: "An obligations matrix by investor, trigger, and owner." },
  "mfn-analysis": { task: "review", gets: "An election matrix with recommendations and assumptions stated." },
  "manrre-reit-conversion": { task: "review", gets: "A conversion-and-closing matrix with legacy conflicts flagged." },
  "precedent-compare": { task: "compare", gets: "A departures table plus a list of missing provisions." },
  "redline-explain": { task: "review", gets: "Edits grouped by issue, plus an email-ready top five." },
  "buyer-seller-flip": { task: "issues", gets: "A targeted issue list with credible alternatives." },
  "defined-term-audit": { task: "review", gets: "A table of errors with proposed corrections and confidence." },
  "proofread": { task: "review", gets: "Only actionable issues, ranked blocking, substantive, cleanup." },
  "negotiation-log": { task: "compare", gets: "A log of positions, movements, and open points by version." },
  "change-control": { task: "extract", gets: "A contract-by-contract table of triggers and deadlines." },
  "contract-matrix": { task: "extract", gets: "One row per contract, every field cited." },
  "consent-list": { task: "checklist", gets: "A consent list separating legal, contractual, and prudent steps." },
  "missing-documents": { task: "list", gets: "A supplemental request list ready to circulate." },
  "risk-summary": { task: "summarize", gets: "A one-page summary with a detailed appendix." },
  "data-room-status": { task: "list", gets: "A status dashboard with blocked workstreams highlighted." },
  "partner-email": { task: "comms", gets: "A short email: status, judgment calls, next deadline." },
  "client-options": { task: "comms", gets: "A client email with options, trade-offs, and a recommendation." },
  "call-agenda": { task: "draft", gets: "An agenda with positions, fallbacks, sequence, and time budget." },
  "meeting-to-actions": { task: "list", gets: "An action list plus a short recap email." },
  "redline-cover": { task: "comms", gets: "A short, neutral cover email for the markup." },
  "deal-summary": { task: "summarize", gets: "A handoff memo separating agreed, proposed, and unknown." },
  "board-consent-authority-audit": { task: "draft", gets: "A table: Action | Required Authority | Source | Approval Threshold | Current Draft Coverage | Missing Approval/Defect | Recommended Fix, followed by a short execution sequence." },
  "board-materials-decision-memo": { task: "summarize", gets: "A concise board memo with sections: Decision Requested; Key Facts; Material Legal/Commercial Terms; Conflicts/Process; Open Items; Resolutions to Be Approved; Source Appendix." },
  "reserved-matters-map": { task: "extract", gets: "A normalized matrix: Action | Approval Right Holder | Threshold | Exceptions | Sunset/Termination | Source | Practical Note." },
  "stockholder-approval-analysis": { task: "extract", gets: "A table: Approval | Holder/Class | Threshold | Source | Interaction with Other Rights | Satisfied? | Action Needed." },
  "director-and-officer-authority-matrix": { task: "extract", gets: "A matrix: Action | Approver | Signatory | Dollar/Other Limit | Delegation Right | Source | Escalation Trigger." },
  "entity-formation-package-review": { task: "compare", gets: "A formation gap list plus a document-by-document correction table." },
  "capitalization-rights-reconciliation": { task: "compare", gets: "A security-level rights matrix plus a list of cap-table/document inconsistencies and missing source documents." },
  "equity-issuance-closing-checklist": { task: "checklist", gets: "A chronological checklist: Item | Source | Responsible Party | Timing | Dependency | Evidence of Completion | Status." },
  "safe-and-convertible-note-conversion-audit": { task: "review", gets: "An instrument-by-instrument calculation specification showing every formula and required input, without inventing missing numbers." },
  "subsidiary-and-entity-structure-map": { task: "extract", gets: "A parent-child hierarchy and a table: Entity | Jurisdiction | Type | Parent | Ownership | Control | Good Standing | Key Documents | Gaps." },
  "customer-msa-playbook-review": { task: "review", gets: "A table: Priority | Section | Counterparty Term | Preferred Position | Fallback | Risk/Impact | Proposed Redline | Escalation Owner." },
  "vendor-agreement-risk-review": { task: "review", gets: "A risk table ranked High/Medium/Low with section citation, issue, consequence, proposed ask, fallback, and client owner." },
  "saas-agreement-review": { task: "issues", gets: "A structured issues list with separate Legal, Security/Privacy, Commercial, and Operational sections." },
  "data-processing-addendum-review": { task: "issues", gets: "A deviation table with issue, source clause, client standard, proposed revision, fallback, and escalation to Privacy/Security." },
  "nda-review-and-redline-instructions": { task: "review", gets: "A concise redline instruction list: Section | Issue | Preferred Change | Fallback | Rationale | Escalate?." },
  "ip-license-scope-analysis": { task: "extract", gets: "A rights map plus a table of ambiguities, overbreadth, missing rights, and proposed drafting fixes." },
  "distribution-agreement-review": { task: "issues", gets: "An issues table with legal/commercial classification and a separate list of terms requiring antitrust or regulatory review." },
  "professional-services-agreement-and-sow-hierarchy-review": { task: "compare", gets: "A document hierarchy, term-by-term conflict matrix, and list of drafting corrections." },
  "draft-agreement-from-approved-precedent": { task: "draft", gets: "A clean draft plus a drafting-notes section listing every place where the inputs were incomplete, inconsistent, or required a legal judgment." },
  "targeted-amendment-with-consequential-effects-check": { task: "draft", gets: "A clean amendment plus a consequential-effects table identifying every related provision reviewed." },
  "defined-term-integrity-audit": { task: "review", gets: "A table: Defined Term | Definition Location | Usage | Problem | Substantive Effect | Proposed Correction | Severity." },
  "cross-reference-and-schedule-audit": { task: "compare", gets: "A table: Reference Location | Current Reference | Expected Target | Problem | Effect | Correction." },
  "missing-provision-audit-against-baseline": { task: "draft", gets: "A table: Baseline Provision | Current Draft Treatment | Missing/Narrowed? | Material Effect | Recommended Action | Source." },
  "multi-document-consistency-audit": { task: "compare", gets: "A cross-document inconsistency matrix ranked by severity and a list of proposed conforming edits." },
  "material-contracts-diligence-matrix": { task: "extract", gets: "A table: Contract | Counterparty | Key Term | Trigger/Risk | Section | Materiality Basis | Consent/Action | Follow-Up." },
  "entity-compliance-and-good-standing-audit": { task: "review", gets: "A status table and prioritized remediation list." },
  "private-offering-exemption-checklist": { task: "checklist", gets: "A source-linked checklist separating facts established, facts needed, filings, deadlines, and legal questions requiring securities-law research." },
  "disclosure-consistency-check": { task: "compare", gets: "A table: Statement/Topic | Source A | Source B | Conflict/Support Issue | Materiality | Required Correction/Verification." },
  "beneficial-ownership-and-control-rights-map": { task: "extract", gets: "A person/entity-level matrix plus unresolved ownership questions." },
  "executed-contract-obligations-tracker": { task: "list", gets: "A table: Obligation | Responsible Party | Trigger | Due Date/Cadence | Notice Method | Evidence | Source | Internal Owner | Escalation." },
  "renewal-and-termination-calendar": { task: "list", gets: "A chronological calendar with earliest action date, latest action date, notice method, consequence, and source." },
  "corporate-records-book-completeness-audit": { task: "compare", gets: "A chronological gap table: Event | Required Corporate Action | Evidence Found | Missing/Defect | Potential Remediation | Priority." },
  "signature-and-execution-audit": { task: "review", gets: "An execution status table and list of curing actions." },
  "negotiation-playbook-from-precedents": { task: "issues", gets: "A matrix: Issue | Preferred Position | Fallback A | Fallback B | Reject/Escalate Trigger | Rationale | Representative Precedent | Decision Owner." },
  "executive-contract-summary": { task: "summarize", gets: "A one-page summary with: What We Agreed; What We Must Do; What Could Cost Us Money; Key Dates; Key Risks; Open Questions; source citations." },
  "board-approval-memo-from-operative-documents": { task: "summarize", gets: "A board approval memo plus an appendix mapping each proposed resolution to its supporting document provision." },
  "targeted-contract-law-research-memo": { task: "summarize", gets: "A concise memo: Question Presented; Contract Text; Governing Law; Primary Authorities; Analysis; Counterarguments; Conclusion; Practical Drafting/Negotiation Implications." },
  "buyer-side-nda-playbook-review": { task: "issues", gets: "A concise deviation table with proposed redline language and fallback." },
  "seller-side-nda-playbook-review": { task: "issues", gets: "A prioritized issues list with seller ask, fallback, and escalation." },
  "nda-redline-to-issues-list": { task: "issues", gets: "A table: Priority | Issue | Sections | Prior Position | New Position | Effect | Recommended Response | Fallback | Client Decision." },
  "clean-team-and-competitively-sensitive-information-protocol": { task: "draft", gets: "A clean draft plus a table of facts that must be confirmed before use." },
  "loi-buyer-side-review": { task: "issues", gets: "A High/Medium/Low issues table and proposed buyer asks." },
  "loi-seller-side-review": { task: "issues", gets: "A seller issues list plus a list of terms that should be nailed down before exclusivity." },
  "term-sheet-to-definitive-document-instruction-set": { task: "extract", gets: "A drafting instruction matrix: Term | Agreed Position | Definitive Document | Section/Concept | Open Issue | Client Owner." },
  "loi-precedent-benchmark": { task: "compare", gets: "A precedent matrix showing common position, range of outcomes, current term, and whether the current term is a true outlier." },
  "buyer-side-stock-purchase-agreement-review": { task: "review", gets: "A table: Priority | Section | Current Position | Buyer Risk | Related Provisions | Buyer Ask | Fallback | Client Decision." },
  "seller-side-stock-purchase-agreement-review": { task: "issues", gets: "A prioritized seller issues list with proposed positions and fallbacks." },
  "asset-purchase-agreement-liability-allocation-review": { task: "extract", gets: "A transfer matrix: Asset/Liability | Treatment | Source | Consent/Condition | Ambiguity | Risk | Proposed Fix." },
  "merger-agreement-deal-protection-review": { task: "extract", gets: "A deal-protection map with triggers, deadlines, board discretion, counterparty rights, and practical process consequences." },
  "working-capital-adjustment-mechanics-audit": { task: "compare", gets: "A mechanics table plus a list of ambiguity/double-counting risks and missing calculation inputs." },
  "earnout-mechanics-audit": { task: "extract", gets: "An earnout risk matrix plus a list of drafting changes needed for objective administration." },
  "purchase-agreement-draft-from-precedent": { task: "draft", gets: "A clean first draft plus drafting notes identifying every provision requiring client or specialist input." },
  "rep-and-covenant-interdependency-map": { task: "extract", gets: "A risk-area matrix: Topic | Rep | Qualifiers | Schedule | Covenant | Bring-Down | Remedy | Survival/RWI | Diligence Evidence | Gap." },
  "mae-definition-and-closing-condition-analysis": { task: "extract", gets: "A contractual analysis table plus a separate section identifying any external-law research needed." },
  "fraud-and-non-reliance-framework-review": { task: "compare", gets: "A framework map with drafting conflicts and residual exposure." },
  "manda-diligence-request-list-builder": { task: "list", gets: "A prioritized request list with request, rationale, likely source, priority, and responsible specialist." },
  "material-contract-diligence-review": { task: "extract", gets: "A contract matrix with source citations and a separate list of required consents and closing dependencies." },
  "change-of-control-and-consent-diligence": { task: "extract", gets: "A consent matrix: Contract | Trigger | Transaction Step | Required Action | Timing | Consequence | Section | Owner." },
  "debt-and-lien-diligence": { task: "extract", gets: "A debt payoff/release matrix and list of closing deliverables." },
  "employment-and-change-in-control-diligence": { task: "extract", gets: "An employee-by-employee matrix plus a list of items requiring benefits/tax specialist review." },
  "ip-ownership-and-license-diligence": { task: "extract", gets: "An IP rights matrix and prioritized ownership/license gaps." },
  "privacy-and-cyber-diligence": { task: "extract", gets: "A risk matrix with legal, technical, operational, and purchase-agreement implications." },
  "real-estate-diligence-for-manda": { task: "list", gets: "A property/site matrix plus a consent and critical-date tracker." },
  "litigation-and-regulatory-diligence": { task: "extract", gets: "A matter matrix ranked by transaction impact and a list of purchase-agreement protections to consider." },
  "diligence-findings-to-executive-red-flag-report": { task: "review", gets: "A concise red-flag report with columns: Issue | Evidence | Transaction Impact | Agreement Response | Action | Owner | Status." },
  "seller-disclosure-schedule-completeness-audit": { task: "review", gets: "A table: Rep | Schedule | Required Disclosure | Current Disclosure | Potential Omission/Defect | Source | Follow-Up | Severity." },
  "buyer-review-of-seller-disclosure-schedules": { task: "issues", gets: "A buyer issues table with rep, disclosure, diligence context, transaction impact, follow-up, and proposed agreement response." },
  "disclosure-schedule-first-draft-from-diligence": { task: "draft", gets: "A section-by-section draft schedule plus an open-items table; do not infer facts or omit a potential responsive item merely because materiality is uncertain." },
  "disclosure-schedule-cross-reference-audit": { task: "compare", gets: "A correction table and a list of schedule sections requiring lawyer review." },
  "disclosure-schedule-change-tracker": { task: "list", gets: "A change log: Schedule | Change | Why It Matters | Agreement/Diligence Driver | Follow-Up | Priority." },
  "representation-coverage-map": { task: "extract", gets: "A risk-to-protection matrix and a list of uncovered or weakly covered issues." },
  "knowledge-qualifier-audit": { task: "review", gets: "A table: Provision | Knowledge Standard | Knowledge Group | Issue | Practical Effect | Proposed Revision." },
  "materiality-scrape-analysis": { task: "extract", gets: "A provision interaction map plus drafting issues and proposed clarifications." },
  "indemnification-waterfall-review": { task: "extract", gets: "A recovery waterfall and claim-path matrix." },
  "closing-condition-bring-down-audit": { task: "review", gets: "A closing-condition table with test, measurement time, source, known issue, cure/waiver path, and owner." },
  "interim-operating-covenant-review": { task: "extract", gets: "A practical restrictions matrix and list of consent items likely to arise before closing." },
  "restrictive-covenant-review": { task: "issues", gets: "A clause-by-clause issues list plus external-law questions requiring specialist review." },
  "tax-covenant-and-indemnity-issue-spot": { task: "checklist", gets: "A tax-issues checklist citing the agreement and clearly labeling items requiring tax-specialist confirmation." },
  "escrow-agreement-consistency-review": { task: "compare", gets: "A consistency table and proposed corrections." },
  "transition-services-agreement-review": { task: "checklist", gets: "An operational/legal issues matrix plus a transition-risk checklist." },
  "rollover-agreement-review": { task: "compare", gets: "A rollover terms matrix and list of inconsistencies with the deal documents." },
  "restrictive-covenant-agreement-consistency-check": { task: "compare", gets: "A comparison table and recommendation for harmonizing terms." },
  "employment-and-retention-agreement-review-for-deal": { task: "compare", gets: "An executive terms summary plus a transaction-document conflict table." },
  "purchase-agreement-markup-to-issues-list": { task: "issues", gets: "A call-ready table ordered High/Medium/Low, followed by New Issues This Turn, Resolved Issues, and Specialist Review Items." },
  "purchase-agreement-precedent-deviation-analysis": { task: "issues", gets: "A deviation table with current language, precedent range, likely reason, client impact, and recommended response." },
  "manda-negotiation-call-sheet": { task: "issues", gets: "A one-page prioritized call sheet plus client-decision questions." },
  "specialist-comment-consolidation": { task: "issues", gets: "A master issues list with specialist owner, source comment, affected provision, current status, and recommended next step." },
  "deal-terms-executive-summary": { task: "summarize", gets: "A two-page summary with Key Economics, Closing Risk, Post-Closing Exposure, Key Dates, and Outstanding Actions." },
  "signing-and-closing-checklist-builder": { task: "checklist", gets: "A checklist: Phase | Item | Source | Responsible Party | Dependency | Due Date | Evidence | Status." },
  "closing-checklist-completeness-audit": { task: "checklist", gets: "A table: Missing/Incorrect Item | Source | Checklist Location | Consequence | Owner | Fix." },
  "funds-flow-verification": { task: "compare", gets: "A sources-and-uses reconciliation with formula references, discrepancies, missing inputs, and wire dependencies; do not invent missing amounts." },
  "post-closing-obligations-tracker": { task: "list", gets: "A chronological tracker with owner, trigger, deadline, notice method, evidence, and source." },
  "purchase-price-adjustment-dispute-analysis": { task: "issues", gets: "An issue-by-issue table with contractual rule, parties' positions, evidence, strengths/weaknesses, and resolution path." },
  "borrower-side-financing-term-sheet-review": { task: "issues", gets: "A borrower issues list with economics, flexibility, execution risk, and proposed asks." },
  "lender-side-financing-term-sheet-review": { task: "issues", gets: "A lender issues list identifying departures from credit approval and required documentary protections." },
  "commitment-letter-conditions-review": { task: "extract", gets: "A conditions matrix with source, standard, borrower/lender risk, and proposed revision." },
  "market-flex-and-fee-letter-analysis": { task: "extract", gets: "A flex matrix: Flex Right | Cap/Limit | Trigger | Economic Effect | Documentary Effect | Consent Needed | Notes." },
  "commitment-package-consistency-audit": { task: "compare", gets: "A cross-document inconsistency table and prioritized correction list." },
  "borrower-side-credit-agreement-review": { task: "issues", gets: "A prioritized borrower issues list with section, current term, impact, proposed ask, fallback, and required financial input." },
  "lender-side-credit-agreement-review": { task: "issues", gets: "A lender deviation/issues table and list of items requiring credit approval." },
  "credit-agreement-draft-from-term-sheet": { task: "draft", gets: "A clean first draft plus a drafting-notes table identifying open business, tax, accounting, and local-law points." },
  "defined-terms-and-covenant-dependency-audit": { task: "compare", gets: "A dependency map showing Definition | Inputs/Referenced Definitions | Downstream Uses | Ambiguity/Inconsistency | Proposed Fix." },
  "mandatory-prepayment-mechanics-review": { task: "checklist", gets: "A source-linked calculation specification and action checklist, with missing inputs clearly identified." },
  "event-of-default-and-cure-analysis": { task: "extract", gets: "A table: Potential Default | Provision | Trigger | Facts | Cure/Grace | Notice | Consequence | Open Question." },
  "assignment-and-lender-voting-rights-audit": { task: "extract", gets: "An assignment/voting matrix and required-consent analysis." },
  "credit-agreement-executive-summary": { task: "summarize", gets: "A concise term sheet-style summary with source citations and a separate list of unusual or high-impact provisions." },
  "debt-basket-capacity-analysis": { task: "extract", gets: "A capacity-route table with formula, required inputs, conditions, overlap risk, and apparent availability." },
  "restricted-payment-capacity-analysis": { task: "list", gets: "A source-linked capacity waterfall and ledger of required historical usage." },
  "investment-basket-capacity-analysis": { task: "extract", gets: "A pathway matrix and list of required financial/history inputs." },
  "lien-capacity-analysis": { task: "extract", gets: "A lien-capacity matrix with lien basket, debt basket dependency, collateral scope, ranking, and required intercreditor action." },
  "incremental-facility-capacity-analysis": { task: "checklist", gets: "An incremental-capacity table and step-by-step incurrence checklist." },
  "unrestricted-subsidiary-designation-analysis": { task: "extract", gets: "A designation pathway table plus before/after covenant consequences." },
  "ebitda-add-back-audit": { task: "extract", gets: "An add-back matrix: Item | Clause | Amount/Input | Cap | Conditions | Evidence | Double-Count Risk | Allowed? | Open Question." },
  "financial-covenant-compliance-test": { task: "review", gets: "A calculation trace with each contractual input, source, arithmetic check, headroom, and unresolved items." },
  "asset-sale-and-reinvestment-capacity-analysis": { task: "extract", gets: "A transaction-step matrix from disposition through final use of proceeds." },
  "available-amount-builder-basket-ledger": { task: "list", gets: "A chronological ledger with source provision, inflow/outflow, amount input, evidence, and remaining balance; leave unknown amounts blank." },
  "security-agreement-review": { task: "issues", gets: "A collateral issues table and a list of perfection deliverables." },
  "guarantee-review": { task: "extract", gets: "A guarantor-by-guarantor matrix and list of legal/local-law questions." },
  "collateral-package-completeness-audit": { task: "extract", gets: "A collateral coverage matrix: Asset/Entity | Required Security | Document | Perfection Step | Status | Gap | Post-Closing Date." },
  "guarantor-coverage-and-release-test": { task: "review", gets: "An entity-level table with guarantor status, trigger, exception, source, and required action." },
  "ucc-and-lien-search-exceptions-review": { task: "extract", gets: "A lien exception matrix with required closing action and evidence." },
  "collateral-release-mechanics-analysis": { task: "checklist", gets: "A release checklist with contractual trigger, documents, filings, approvals, and sequencing." },
  "intercreditor-agreement-review": { task: "extract", gets: "A rights-by-scenario matrix plus issues requiring restructuring counsel." },
  "abl-term-loan-intercreditor-analysis": { task: "extract", gets: "A collateral-class matrix and enforcement scenario table." },
  "subordination-agreement-review": { task: "review", gets: "A scenario table showing whether the proposed action is permitted and what consents/notices are required." },
  "intercreditor-bankruptcy-scenario-analysis": { task: "extract", gets: "A creditor-class rights matrix, followed by a separate list of enforceability issues requiring bankruptcy-law research." },
  "conditions-precedent-checklist": { task: "checklist", gets: "A CP checklist with condition, source, deliverable, responsible party, dependency, waiver right, and status." },
  "existing-cp-checklist-audit": { task: "checklist", gets: "A gap table and corrected checklist entries." },
  "legal-opinion-coverage-matrix": { task: "draft", gets: "A matrix: Required Opinion | Entity/Document | Draft Coverage | Qualification | Gap | Responsible Counsel." },
  "financing-funds-flow-verification": { task: "compare", gets: "A reconciled sources-and-uses table with discrepancies, missing inputs, and wire dependencies." },
  "amendment-consent-and-sacred-rights-analysis": { task: "extract", gets: "A provision-by-provision consent matrix with required percentage/class and rationale." },
  "waiver-request-analysis": { task: "issues", gets: "A waiver issues list plus proposed narrow drafting instructions." },
  "amendment-conforming-changes-audit": { task: "review", gets: "A conforming-change table and a clean list of provisions that should be updated in an amended-and-restated or conformed version." },
  "credit-agreement-markup-to-issues-list": { task: "issues", gets: "A prioritized table with issue, sections, old/new position, impact, ask, fallback, and required credit/client decision." },
  "financing-precedent-comparison": { task: "compare", gets: "A deviation matrix with precedent range, current position, likely reason, and negotiation significance." },
  "financing-deal-summary": { task: "review", gets: "A term-sheet style summary plus a list of operational compliance items and key source citations." },
  "borrower-compliance-calendar": { task: "list", gets: "A calendar: Obligation | Trigger/Cadence | Due Date Rule | Notice Method | Source | Internal Owner | Evidence | Escalation." },
  "compliance-certificate-verification": { task: "review", gets: "A verification table identifying each certificate statement, source support, arithmetic check, missing evidence, and issue." },
  "first-day-motion-fact-verification": { task: "review", gets: "A statement-to-source audit: Motion/Paragraph | Statement | Source | Supported? | Discrepancy | Required Fix/Client Confirmation." },
  "first-day-relief-matrix": { task: "extract", gets: "A motion-by-motion matrix with relief, cap, key conditions, objection risk, hearing date, and owner." },
  "docket-order-and-deadline-tracker": { task: "list", gets: "A chronological table: Date | Event/Deadline | Source Docket No./Paragraph | Responsible Party | Consequence | Status." },
  "first-day-order-vs-motion-comparison": { task: "compare", gets: "A table: Issue | Motion Request | Proposed Order | Entered Order | Effect | Required Operational Follow-Up." },
  "chapter-11-case-opening-executive-brief": { task: "summarize", gets: "A two-page brief with Key Facts, Capital Structure, Proposed Path, Immediate Risks, Key Dates, and Questions." },
  "restructuring-support-agreement-review": { task: "list", gets: "A provision map plus a separate milestone calendar and client-decision list." },
  "rsa-milestone-and-termination-trigger-tracker": { task: "list", gets: "A chronological table: Milestone/Trigger | Date/Test | Source | Cure/Extension | Waiver Holder | Consequence | Status." },
  "out-of-court-exchange-offer-document-review": { task: "extract", gets: "An issues matrix plus required consent/threshold calculations." },
  "consent-solicitation-threshold-analysis": { task: "extract", gets: "A provision-by-provision consent matrix and list of amendments that cannot be achieved through the proposed consent mechanism." },
  "restructuring-term-sheet-to-document-workplan": { task: "review", gets: "A workplan: Term | Required Document/Action | Responsible Workstream | Dependency | Consent | Timing | Open Issue." },
  "dip-credit-agreement-review": { task: "issues", gets: "A DIP issues table plus a separate credit-agreement-to-order inconsistency matrix." },
  "dip-order-hot-provisions-review": { task: "extract", gets: "A hot-provisions matrix with current term, client impact, precedent position, proposed revision, and escalation." },
  "dip-credit-agreement-vs-dip-order-audit": { task: "compare", gets: "A cross-document conflict table with which document controls and recommended conforming action." },
  "cash-collateral-order-review": { task: "issues", gets: "A stakeholder-impact matrix and negotiation issues list." },
  "dip-budget-covenant-tracker": { task: "list", gets: "A weekly tracker with covenant, period, budget, actual, variance, threshold, status, and source." },
  "plan-of-reorganization-treatment-matrix": { task: "compare", gets: "A class-by-class treatment matrix with source citations and inconsistencies between plan and disclosure statement." },
  "plan-and-disclosure-statement-consistency-audit": { task: "compare", gets: "A discrepancy table ranked by materiality and required correction owner." },
  "plan-waterfall-and-recovery-verification": { task: "compare", gets: "A class-by-class reconciliation showing legal entitlement, model input, modeled recovery, discrepancy, and unresolved assumptions." },
  "release-exculpation-and-injunction-review": { task: "extract", gets: "A stakeholder-by-stakeholder rights matrix plus legal research questions if external law review is permitted." },
  "effective-date-conditions-checklist": { task: "checklist", gets: "A chronological checklist with source paragraph, responsible party, dependency, waiver holder, evidence, and status." },
  "creditor-position-and-recovery-analysis": { task: "summarize", gets: "A creditor position memo with a rights/recovery matrix and open legal/valuation questions." },
  "proof-of-claim-review": { task: "review", gets: "A claim review table with supported amount, disputed components, evidence, potential objection grounds, and follow-up." },
  "claims-objection-package-builder": { task: "draft", gets: "A draft objection schedule plus claim-by-claim evidentiary support table; do not assert a ground not supported by the record." },
  "executory-contract-assumption-rejection-matrix": { task: "extract", gets: "A matrix: Contract | Counterparty | Cure | Key Rights | Operational Value | Proposed Treatment | Deadline | Issue | Source." },
  "cure-claim-reconciliation": { task: "compare", gets: "A contract-by-contract cure reconciliation with amount supported, amount disputed, evidence, and resolution path." },
  "section-363-bidder-compliance-checklist": { task: "checklist", gets: "A chronological bidder checklist plus a separate Hard Stop list of bid-disqualification risks." },
  "363-apa-buyer-side-review": { task: "issues", gets: "A bidder issues list separating agreement points from bankruptcy-order points." },
  "sale-order-vs-apa-consistency-audit": { task: "compare", gets: "A consistency table with required order revisions or APA conforming changes." },
  "bid-comparison-matrix": { task: "compare", gets: "A normalized bid matrix and a separate list of non-price execution risks." },
  "liability-management-documentary-capacity-screen": { task: "extract", gets: "A transaction-step pathway matrix followed by Documentary Blockers, Required Votes, Required Financial Inputs, and External-Law Questions." },
  "uptier-exchange-consent-path-analysis": { task: "extract", gets: "A step-by-step consent and documentary pathway with adverse-readings section." },
  "drop-down-unrestricted-subsidiary-capacity-analysis": { task: "extract", gets: "A transfer-step matrix showing authority, basket usage, release effect, required valuation/input, and blocker." },
  "intercreditor-rights-in-restructuring-scenario": { task: "extract", gets: "A creditor-class rights matrix plus separate enforceability and bankruptcy-law research questions." },
  "restructuring-chronology-builder": { task: "review", gets: "A chronology: Date | Event | Parties | Source | Legal/Commercial Significance | Disputed/Unclear? | Follow-Up." },
  "weekly-restructuring-client-update": { task: "summarize", gets: "A client-ready update with sections: What Changed; Why It Matters; Decisions Needed; Key Dates; Next Steps; source references." },
  "buyer-side-psa-review": { task: "issues", gets: "A buyer issues list with section, risk, ask, fallback, and client decision." },
  "seller-side-psa-review": { task: "issues", gets: "A seller issues list with proposed positions and fallbacks." },
  "psa-draft-from-loi-and-precedent": { task: "draft", gets: "A clean draft plus open drafting questions and missing property-specific inputs." },
  "psa-critical-dates-extract": { task: "extract", gets: "A chronological critical-date table with trigger, earliest/latest date, notice method, responsible party, consequence, and source." },
  "psa-closing-deliverables-checklist": { task: "checklist", gets: "A closing checklist with source, responsible party, prerequisite, execution/notary requirement, and status." },
  "psa-markup-to-negotiation-issues": { task: "issues", gets: "A prioritized issue table with old/new position, practical effect, ask, fallback, and client decision." },
  "tenant-side-lease-review": { task: "issues", gets: "A tenant issues list ranked by economic, operational, and legal impact." },
  "landlord-side-lease-review": { task: "issues", gets: "A landlord issues list with preferred position, fallback, and building-operations impact." },
  "lease-abstraction-with-amendment-tracing": { task: "review", gets: "A current-term abstract with source document for every field plus a separate critical-date table." },
  "lease-operating-expense-audit": { task: "review", gets: "A contract-to-charge variance table with lease rule, billed treatment, amount/input, discrepancy, and follow-up." },
  "renewal-and-expansion-option-analysis": { task: "list", gets: "An option calendar with earliest/latest exercise dates, conditions, pricing mechanism, and source." },
  "assignment-and-change-of-control-analysis": { task: "extract", gets: "A transaction-step table with trigger, exception, required notice/consent, conditions, and risk." },
  "tenant-estoppel-vs-lease-reconciliation": { task: "compare", gets: "A discrepancy table with estoppel statement, operative lease term, source, risk, and proposed correction." },
  "lease-negotiation-call-sheet": { task: "issues", gets: "A one-page prioritized call sheet plus Points Not Worth Spending Negotiating Capital On." },
  "real-estate-loan-agreement-review": { task: "issues", gets: "A prioritized issues table plus operational compliance items." },
  "mortgage-deed-of-trust-review": { task: "issues", gets: "A collateral consistency table and title/legal-description issues list." },
  "bad-boy-guaranty-review": { task: "extract", gets: "A trigger-by-trigger matrix with exposure type, causation standard, cure if any, and proposed revision." },
  "loan-document-consistency-audit": { task: "compare", gets: "A cross-document inconsistency matrix with proposed conforming edits." },
  "real-estate-loan-closing-checklist": { task: "checklist", gets: "A chronological checklist with condition, source, party, dependency, evidence, and status." },
  "real-estate-jv-agreement-review": { task: "extract", gets: "A governance/economics issues matrix with proposed positions and fallbacks." },
  "jv-waterfall-specification-audit": { task: "compare", gets: "A tier-by-tier legal-to-model reconciliation and unresolved calculation assumptions." },
  "development-agreement-review": { task: "list", gets: "A risk matrix plus a milestone/approval tracker." },
  "development-entitlement-condition-tracker": { task: "list", gets: "A chronological tracker with condition, agency, source, due date/trigger, dependency, evidence, owner, and status." },
  "property-management-agreement-review": { task: "extract", gets: "An authority/fee/risk matrix and list of owner-approval thresholds." },
  "title-commitment-and-survey-review": { task: "review", gets: "A table: Exception | Title Citation | Survey Reference | Effect | PSA/Loan Treatment | Risk | Cure/Action | Responsible Party | Deadline." },
  "title-objection-letter-builder": { task: "draft", gets: "A draft objection letter plus an internal table explaining each objection, contractual basis, and fallback." },
  "recorded-document-restriction-abstract": { task: "extract", gets: "A document-by-document matrix with burden/benefit, parties, term, approval rights, cost obligations, and property impact." },
  "survey-exception-issue-spot": { task: "issues", gets: "An issue table with location/reference, legal document if any, effect, cure, and title-objection recommendation." },
  "title-and-survey-closing-cure-tracker": { task: "list", gets: "A cure tracker: Issue | Required Cure | Responsible Party | Deadline | Evidence | Title Company Confirmation | Status." },
  "real-estate-diligence-request-list": { task: "list", gets: "A prioritized request list with purpose, likely source, owner, and follow-up trigger." },
  "service-contract-and-vendor-diligence": { task: "extract", gets: "A contract matrix with proposed closing treatment and required notice/consent." },
  "zoning-and-land-use-document-review": { task: "extract", gets: "A land-use matrix plus issues requiring local land-use counsel confirmation." },
  "environmental-diligence-issue-matrix": { task: "extract", gets: "A risk matrix with factual basis, legal/contract implications, follow-up, and specialist questions." },
  "snda-review": { task: "issues", gets: "A tenant/lender issues table with proposed revisions and fallbacks." },
  "portfolio-estoppel-reconciliation": { task: "compare", gets: "A portfolio exception matrix with tenant, field, estoppel statement, lease term, discrepancy, materiality, and cure/follow-up." },
  "estoppel-and-snda-closing-tracker": { task: "list", gets: "A tenant-by-tenant tracker with requirement, status, deviation, approval needed, and closing impact." },
  "real-estate-closing-checklist": { task: "checklist", gets: "A phased checklist with item, source, party, dependency, execution/recording requirements, and status." },
  "proration-and-settlement-statement-verification": { task: "review", gets: "A line-item verification table with contract rule, source data, calculation, discrepancy, and open item." },
  "critical-dates-portfolio-calendar": { task: "list", gets: "A chronological calendar with document, obligation/right, trigger, deadline, notice method, owner, consequence, and source." },
  "real-estate-document-markup-to-issues-list": { task: "issues", gets: "A prioritized issue table with old/new position, practical effect, ask, fallback, and client decision." },
  "real-estate-negotiation-strategy": { task: "issues", gets: "A one-page call sheet plus an escalation list." },
  "lpa-manager-side-review": { task: "compare", gets: "A manager issues matrix plus a list of terms requiring tax/regulatory/finance specialist confirmation." },
  "investor-side-lpa-review": { task: "issues", gets: "A High/Medium/Low investor issues list with requested side-letter or LPA protection where appropriate." },
  "lpa-draft-from-prior-fund-and-term-sheet": { task: "draft", gets: "A clean first draft plus a change log identifying every intentional deviation from the prior fund." },
  "prior-fund-vs-new-fund-lpa-comparison": { task: "compare", gets: "A vintage-change matrix with prior term, new term, rationale if known, investor impact, operational impact, and open question." },
  "key-person-provision-analysis": { task: "extract", gets: "A key-person scenario matrix with trigger, consequence, cure, vote, source, and side-letter variation." },
  "removal-and-no-fault-rights-analysis": { task: "issues", gets: "A rights-by-scenario matrix and negotiation issues list." },
  "lpa-defined-term-and-cross-reference-audit": { task: "compare", gets: "A correction table with substantive effect and severity." },
  "ppm-to-lpa-consistency-audit": { task: "compare", gets: "A discrepancy table with PPM statement, LPA term, materiality, and required correction owner." },
  "ppm-risk-factor-gap-review": { task: "compare", gets: "A risk-factor gap matrix distinguishing prior-fund boilerplate from current-fund-specific risks." },
  "subscription-agreement-review": { task: "checklist", gets: "An issues list plus a missing-information/KYC checklist." },
  "investor-subscription-package-verification": { task: "review", gets: "A closing-readiness table with missing item, source, owner, and status." },
  "subscription-agreement-change-tracker": { task: "list", gets: "A change matrix with investor impact, operational impact, and reason/owner if known." },
  "manager-side-side-letter-review": { task: "list", gets: "An Executive Summary, Key Terms Matrix, Operational Obligation Register, MFN Analysis, Potential Governing-Document Conflicts, Missing/Not Found, and Human Review Questions." },
  "investor-side-side-letter-request-review": { task: "extract", gets: "An investor request matrix with requested right, current fund treatment, gap, proposed language, fallback, and priority." },
  "cross-investor-side-letter-matrix": { task: "extract", gets: "A matrix plus separate MFN Exposure, Operational Burden, Potential Precedent, and Human Review tables." },
  "mfn-eligibility-analysis": { task: "extract", gets: "A right-by-right MFN table: Source Investor | Right | Eligible? | Exclusion/Threshold | Election Requirement | Deadline | Citation | Open Question." },
  "mfn-election-package-verification": { task: "review", gets: "A verification table plus a list of rights requiring legal judgment or manager approval." },
  "side-letter-clause-draft-from-precedent": { task: "draft", gets: "Proposed clause language plus a precedent/MFN impact note and open implementation questions." },
  "side-letter-operational-obligations-register": { task: "list", gets: "A register: Investor | Obligation | Trigger/Cadence | Due Date | Source | Internal Owner | Evidence | Escalation | Status." },
  "lpa-to-side-letter-conflict-audit": { task: "compare", gets: "A conflict matrix: Side Letter Term | Governing Provision | Conflict/Modification | Effect | Drafting Fix/Clarification | Human Review." },
  "management-agreement-review": { task: "compare", gets: "An authority/economics/risk matrix and cross-document consistency issues." },
  "gp-agreement-review": { task: "compare", gets: "A member/partner rights matrix and list of conflicts with fund-level documents." },
  "management-company-agreement-review": { task: "extract", gets: "A governance/economics matrix and departure-scenario analysis." },
  "gp-manager-document-suite-consistency-audit": { task: "compare", gets: "A cross-document consistency matrix and prioritized conforming changes." },
  "investor-ddq-response-drafting-with-source-controls": { task: "draft", gets: "The draft DDQ plus a verification table: Question | Draft Answer | Source | Approval Status | Conflict | Calculation Required | Compliance Review | Open Item." },
  "investor-request-to-negotiation-issues-list": { task: "issues", gets: "A prioritized table with investor ask, current fund term, precedent position, manager preferred response, fallback, and approval owner." },
  "investor-negotiation-call-sheet": { task: "issues", gets: "A one-page prioritized call sheet plus items requiring IC/COO/Compliance approval." },
  "investor-diligence-request-tracker": { task: "list", gets: "A tracker: Request | Investor | Category | Source/Owner | Draft Response | Approval | Deadline | Status | Open Issue." },
  "most-favored-investor-precedent-impact-review": { task: "summarize", gets: "A precedent-impact memo with comparable terms, MFN exposure, operational impact, and recommended drafting guardrails." },
  "investment-adviser-regulatory-obligations-map": { task: "extract", gets: "A source-linked obligations matrix separating confirmed facts, legal conclusions, recurring filings, policies, and open questions." },
  "fund-marketing-rule-review": { task: "review", gets: "A claim-by-claim substantiation table with source, disclosure, compliance issue, and required correction/approval." },
  "form-adv-consistency-review": { task: "compare", gets: "A discrepancy table with source, current fact, filing statement, materiality, and action owner." },
  "conflicts-inventory-builder": { task: "list", gets: "A conflicts register with source, affected parties, mitigation, disclosure, approval process, and monitoring owner." },
  "regulatory-change-impact-assessment": { task: "summarize", gets: "A memo: Rule Summary; Applicability; Current-State Gap; Required Document Changes; Policy/Process Changes; Owner; Deadline; Open Legal Questions." },
  "fund-terms-comparison-for-investor": { task: "compare", gets: "A normalized comparison table plus a concise investor-facing summary of the most consequential differences." },
  "investor-update-source-verification": { task: "summarize", gets: "A statement-to-source table and corrected language for unsupported or overbroad statements." },
  "investor-notice-drafting-from-governing-documents": { task: "checklist", gets: "A clean notice plus an internal compliance checklist confirming the contractual notice requirements." },
  "fees-and-expenses-allocation-audit": { task: "extract", gets: "An allocation matrix plus a list of ambiguous or policy-sensitive expense categories." },
  "waterfall-and-carried-interest-specification": { task: "compare", gets: "A tier-by-tier legal-to-model reconciliation and list of missing calculation inputs." },
  "management-fee-calculation-audit": { task: "review", gets: "An investor-by-investor fee calculation trace with source and discrepancy." },
  "continuation-vehicle-conflict-review": { task: "checklist", gets: "A rights/consent/conflict matrix plus a transaction process checklist." },
  "key-governance-rights-matrix": { task: "extract", gets: "An investor/right matrix with threshold, trigger, source, and operational owner." },
  "fund-closing-checklist": { task: "checklist", gets: "A closing checklist with investor-specific and fund-level workstreams, dependencies, responsible party, and evidence." },
  "investor-closing-readiness-matrix": { task: "extract", gets: "An investor-by-investor readiness matrix with blocker, owner, action, and status." },
  "fund-compliance-obligations-tracker": { task: "list", gets: "A calendar/register: Obligation | Fund/Investor | Trigger/Cadence | Due Date | Source | Owner | Evidence | Escalation | Status." },
};

// Extra search vocabulary — lawyer terminology that does not appear in prompt titles.
export const SEARCH_SYNONYMS: Record<string, string> = {
  "purchase-agreement-issues": "spa apa merger agreement negotiation points markup buyer seller reps",
  "ma-diligence": "data room due diligence red flag report",
  "credit-agreement-summary": "loan agreement facility summary term extraction lma",
  "covenant-capacity": "restricted payment basket incurrence debt capacity",
  "precedent-compare": "form template markup redline against precedent",
  "negotiation-log": "versions turns drafts history blackline",
  "psa-issue-list": "real property sale contract issues",
  "lease-abstract": "tenant landlord rent roll abstract summary",
  "change-control": "coc assignment anti-assignment consent",
  "risk-summary": "executive summary findings memo to partner",
  "partner-email": "update supervising partner status note",
  "closing-checklist": "signing closing agenda deliverables",
  "conditions-precedent": "cp list closing conditions financing",
  "defined-term-audit": "typos cross references cleanup qc",
  "proofread": "execution version signature pages final check",
  "plan-disclosure": "chapter 11 plan ds solicitation",
  "first-day-motions": "first day relief bankruptcy filing",
  "lpa-terms": "limited partnership agreement fund terms",
  "mfn-analysis": "most favoured nation side letter election",
  "term-sheet-consistency": "loi heads of terms definitive agreement",
};
